************ MODIFY THE DATA ************;
Data ORION.TRAIN;
set ORION.TRAINING;
************* DROP EMPTY VARIABLE ***********************;
if ID = 591 then delete;
************* TRANSFORM YEAR ***********************;
YEAR = 2018 - YEAR;
************ ONE LABEL ENCODING ************;
************ FUEL_TYPE ************;
if FUEL_TYPE = 'Бензин' then FT = 1;
if FUEL_TYPE = 'Бензин-Газ' then FT = 2;
if FUEL_TYPE = 'Газ' then FT = 3;
if FUEL_TYPE = 'Гибрид' then FT = 4;
if FUEL_TYPE = 'Дизель' then FT = 5;
************ BODY_TYPE ************;
if BODY_TYPE = 'Внедорожник' then BT = 1;
if BODY_TYPE = 'Кроссовер' then BT = 2;
if BODY_TYPE = 'Минивэн' then BT = 3;
if BODY_TYPE = 'Пикап' then BT = 4;
if BODY_TYPE = 'Седан' then BT = 5;
if BODY_TYPE = 'Универсал' then BT = 6;
if BODY_TYPE = 'Хэтчбек/Лифтбек' then BT = 7;
************ TYPE_OF_DRIVE ************;
if TYPE_OF_DRIVE = 'Задний привод' then TOD = 1;
if TYPE_OF_DRIVE = 'Передний привод' then TOD = 2;
if TYPE_OF_DRIVE = 'Полный привод' then TOD = 3;
************ INTERIOR_TYPE ************;
if INTERIOR_TYPE = 'ВЕЛЮР' then IT = 1;
if INTERIOR_TYPE = 'КОЖА' then IT = 2;
if INTERIOR_TYPE = 'КОМБИНИРОВАННЫЙ' then INTERIOR_TYPE = 3;
************ TRANSM_TYPE ************;
if TRANSM_TYPE = 'АКПП' then TT = 1;
if TRANSM_TYPE = 'МКПП' then TT = 2;
************ AUTO_CONDITION ************;
if AUTO_CONDITION = 'Отличное' then AC = 1;
if AUTO_CONDITION = 'Удовлетворительное' then AC = 2;
if AUTO_CONDITION = 'Хорошее' then AC = 3;
************ CHANGING FORMAT ************;